Repository linz/postgresql-tableversion, pull requests merged in 2018-02, with the labels that each got.

#84 [test_all_upgrades] Do not force use of `sudo`
  .travis.yml
  test/ci/test_all_upgrades.sh
Labels: enhancement

#83 [test_all_upgrades] Do not force use of `sudo`
  .travis.yml
  test/ci/test_all_upgrades.sh
Labels: enhancement

#82 [1.4] Do not force revision sequence reset on upgrade
  CHANGELOG.md
  sql/00-config_tables.sql
Labels: bug

#85 [test_all_upgrades] Do not force use of `sudo`
  .travis.yml
  test/ci/test_all_upgrades.sh
Labels: enhancement

#73 New test added + travis dep line
  .travis.yml
Labels: testsuite

#90 [1.4] Add ver_fix_revision_disorder function
  CHANGELOG.md
  sql/17-fix_revision_disorder.sql
Labels: enhancement

#91 [1.3] Add ver_fix_revision_disorder function
  CHANGELOG.md
  sql/17-fix_revision_disorder.sql
Labels: enhancement

#94 Have disable_versioning drop all associated objects
  CHANGELOG.md
  sql/02-disable_versioning.sql
  test/sql/base.pg
Labels: enhancement
